Portfolio deployment accessibility test : module1
yusufyusie/yusufyusie.github.io pull request #3
Opened 2023-06-13 17:45 UTC by yusufyusie

### Deployment accessibility test milestone: module 1
**In this milestone of your portfolio website evaluation: we get and**
 "Page titles - no issues found"

- "Image text alternatives- no issues found"
- "text headings -  h1 is not set as similar as title and h1 headings are not settled in the similar format and styles"
- "Color contrast -   no issues found"
- "Resize -  no issues found"
- "Moving content -  no issues found"
- "Multimedia -  no issues found this because there is no video on the live demo of the portfolio"
- "Basic structure of the page check  - there one thing that to is changed because when the website display resolution changes some of text overlaps on the background image that results some unconfertible issues"

2023-06-13 18:07 UTC, Ofarouq310 requested changes
Hi @yusufyusie & @lewisjn-arch, ✋  

Good job so far! 💪 
There are some issues that you still need to work on to go to the next project but you are almost there! 🥈 

![giphy](https://github.com/yusufyusie/yusufyusie.github.io/assets/102612396/61781461-bbfa-489b-b002-da0e823d00b1)

## Highlights
✅ Descriptive PR title.

## Required Changes ♻️

- [ ] Kindly make sure that any changes or accessibility issues you have fixed, you should link to the corresponding line of code in the Pull Request changes, to get a better understanding of how to do so, please refer to this [tutorial](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148).

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 18:07 UTC, Ofarouq310 commented on README.md
- [ ] Kindly take a look at your `README`, it looks like it is two `README` files overlapping and mixed up with each other.

2023-06-13 18:07 UTC, Ofarouq310 commented on index.html
>                      </a>
[OPTIONAL] 
- [ ] Kindly close your paragraph tag correctly.
```suggestion
                    <a href="#footer-container-id" class="link-contact"><p>
                        Contact </p>
                    </a>
```

2023-06-13 19:40 UTC, Ofarouq310 requested changes
Hi @yusufyusie, @paulshaun-kdtk & @lewisjn-arch, ✋  

Good job so far! 💪 
There are some issues that you still need to work on to go to the next project but you are almost there! 🥈 

![giphy](https://github.com/yusufyusie/yusufyusie.github.io/assets/102612396/e3ab36bb-868b-46ca-b6ef-bd72c4f05472)

## Highlights
✅ Descriptive PR title.

## Required Changes ♻️

- [ ] You still did not add  the accessibility changes links in your pull request, you should have added the links in your pull request beside their corresponding point, for example, let's say you made changes concerning the second point, which is "text headings", so besides that point in your PR, you should add your link, e.g.:
    - "text headings - h1 is not set as similar as title and h1 headings are not settled in the similar format and styles" - changes made on line [`64`](https://github.com/yusufyusie/yusufyusie.github.io/blob/b64c7fdd5d3a30fa73206e937846983a2a526c0a/index.html#LL64C10-L64C10).
    - That is how it is written:         
      ![image](https://github.com/yusufyusie/yusufyusie.github.io/assets/102612396/4baf98a2-565c-41b5-8700-ab57a5745807)


- [ ] Kindly make sure to check your `README` file because it is more than one `README combined together.
  
  ![image](https://github.com/yusufyusie/yusufyusie.github.io/assets/102612396/cc13a395-9549-48e6-ac60-2e5f64251095)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 06:46 UTC, lewisjn-arch commented
#### This third review request has:


- [ ] Text headings - h1 is not set as similar as title and h1 headings are not settled in the similar format and styles" - changes made on line `64`
- [ ] Updated README.md file and added collaborators.

2023-06-14 16:45 UTC, abdallahmalima approved these changes
Hi @yusufyusie , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Report includes a check about page titles.✔️
- Report includes a check about image text alternatives.✔️
- Report includes a check about colour contrast.✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._✔️

2023-06-19 06:26 UTC, merged